### ISSUE TITLE
-g is throwing error on --upgrade

### ISSUE THREAD

**Issue by r2liquibase** [liquibase/liquibase-package-manager#184]
**Describe the bug**
Using -g for --upgrade is throwing error.

**To Reproduce**

C:\dev\liquibase\liquibase-4.17.2>lpm upgrade --global
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x9696d9]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0)
        /Users/mcred/projects/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x39
github.com/hashicorp/go-version.(*Version).Compare(0xc0000d0280, 0x0)
        /Users/mcred/projects/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x3b
github.com/hashicorp/go-version.(*Version).LessThan(...)
        /Users/mcred/projects/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:308
package-manager/internal/app/packages.Package.GetLatestVersion({{0xc0000121e0, 0x11}, {0xc000588e90, 0x9}, {0xc000066d80, 0x2a, 0x2a}}, 0xc000066d80?)
        /Users/mcred/projects/liquibase/package-manager/internal/app/packages/Package.go:23 +0x1ab
package-manager/internal/app/packages.Packages.GetOutdated({0xc000076000?, 0x170f453ffff?, 0x197?}, 0x2030000?, {0xc0000d8400, 0x7, 0x8})
        /Users/mcred/projects/liquibase/package-manager/internal/app/packages/Packages.go:41 +0x205
package-manager/internal/app/commands.glob..func7(0xf5f6c0?, {0xc1ce63?, 0x1?, 0x1?})
        /Users/mcred/projects/liquibase/package-manager/internal/app/commands/upgrade.go:24 +0x5f
github.com/spf13/cobra.(*Command).execute(0xf5f6c0, {0xc000089200, 0x1, 0x1})
        /Users/mcred/projects/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xf5ee20)
        /Users/mcred/projects/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mcred/projects/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
package-manager/internal/app/commands.Execute({0xc0000c8360?, 0xc0000c8330?}, {0xc1c8a4, 0x1})
        /Users/mcred/projects/liquibase/package-manager/internal/app/commands/root.go:39 +0x125
main.main()
        /Users/mcred/projects/liquibase/package-manager/cmd/lpm/windows.go:49 +0x2a9

C:\dev\liquibase\liquibase-4.17.2>lpm upgrade
You have no outdated packages installed.
C:\dev\liquibase\liquibase-4.17.2/liquibase_libs/

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mcred** [comment]
Do you have any packages installed globally? What is the output from `lpm ls -g`?

**Comment by mcred** [comment]
Do you have an env for `LIQUIBASE_HOME`?

**Comment by r2liquibase** [comment]
`C:\dev\liquibase\liquibase-4.17.2>lpm ls -g
C:\dev\liquibase\liquibase-4.17.2\lib\
     Package                                Category
├──  mongodb@3.12.11                        driver
└──  liquibase-mongodb@4.17.2               extension`

`C:\dev\liquibase-kubernetes\spring>env | grep LIQUIBASE_HOME
LIQUIBASE_HOME=C:\dev\liquibase\liquibase-4.17.2`

**Comment by r2liquibase** [comment]
`lpm update` solved the issue. Thanks!
