### ISSUE TITLE
Add Oracle jdbc 8 version 21.12.0.0

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-package-manager#344]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Oracle jdbc 8 version 21.12.0.0.  This the latest 21 version available.

Please include 21.12 for oraclepki, oracle-osdt-cert, and oracle-osdt-core also.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mcred** [comment]
This release does not exist in Maven Central: https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/

Where do you see this release? lpm won't be able to add it unless it's published to maven central.

**Comment by doakd** [comment]
21.12 and 21.13 are available on Oracle's site:

21.13:
https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html

21.12:
https://www.oracle.com/database/technologies/appdev/jdbc-drivers-archive.html

**Comment by mcred** [comment]
I don't know why there was a delay, but they are in maven central now and the automation picked them up: https://github.com/liquibase/liquibase-package-manager/pull/346. You should be able to start using them after running `lpm update`.
